#! /bin/bash

################################################################################
################################################################################
################################################################################
TARGET=/opt/share/ngine
\cp -rfp $TARGET/nxx/ .
\cp -rfp $TARGET/addon/ .
\cp -rfp $TARGET/dccf/ .
\cp -rfp $TARGET/dpcf/ .
\cp -rfp $TARGET/dzcf/ .
\cp -rfp $TARGET/i/ .
\cp -rfp $TARGET/n/ .
\cp -rfp $TARGET/z/ .
