//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by liteConsole32.rc
//
#define IDD_DIALOG                      101
#define IDD_FORMVIEW_MAIN               103
#define IDD_FORMVIEW_DRAW               107
#define IDD_FORMVIEW_CRYPTOSYSTEM       108
#define IDD_FORMVIEW_PRIME              108
#define IDD_FORMVIEW_RSA                109
#define IDD_FORMVIEW_BITMAP             110
#define IDD_FORMVIEW_WSC                112
#define IDD_FORMVIEW_WSGW               113
#define IDI_ICON1                       115
#define IDC_BUTTON_SERIAL_OPEN_CLOSE    1001
#define IDC_EDIT_SERIAL_PORT            1002
#define IDC_EDIT_SERIAL_BAUD            1003
#define IDC_EDIT_SERIAL_DBIT            1004
#define IDC_EDIT_SERIAL_SBIT            1005
#define IDC_EDIT_SERIAL_PBIT            1006
#define IDC_EDIT_SERIAL_WRITE           1007
#define IDC_BUTTON_SERIAL_WRITE         1008
#define IDC_COMBO_SERIAL_DISPLAY_TYPE_R 1009
#define IDC_BUTTON_CLEAR                1010
#define IDC_CHECK_READ_YN               1011
#define IDC_LIST_READ                   1012
#define IDC_COMBO_SERIAL_DISPLAY_TYPE_W 1013
#define IDC_CHECK_SERIAL_CR             1014
#define IDC_CHECK_SERIAL_LF             1015
#define IDC_EDIT_NET_IP                 1016
#define IDC_NET_EDIT_IP                 1016
#define IDC_EDIT_NET_PORT               1017
#define IDC_NET_EDIT_PORT               1017
#define IDC_COMBO_NET_PROTOCOL          1018
#define IDC_NET_COMBO_PROTOCOL          1018
#define IDC_COMBO_NET_CS                1019
#define IDC_NET_COMBO_CS                1019
#define IDC_COMBO_NET_CASTTYPE          1020
#define IDC_BUTTON_NET_OPEN_CLOSE       1021
#define IDC_EDIT_NET_WRITE              1022
#define IDC_BUTTON_NET_WRITE            1023
#define IDC_CHECK_NET_CR                1024
#define IDC_CHECK_NET_LF                1025
#define IDC_COMBO_NET_DISPLAY_TYPE_W    1026
#define IDC_COMBO_NET_DISPLAY_TYPE_R    1027
#define IDC_EDIT_WS_URL                 1028
#define IDC_COMBO_WS_CS                 1029
#define IDC_EDIT_SERIAL_PORT2           1030
#define IDC_EDIT_SERIAL_BAUD2           1031
#define IDC_EDIT_SERIAL_DBIT2           1032
#define IDC_COMBO_WS_DISPLAY_TYPE_W     1033
#define IDC_COMBO_WS_DISPLAY_TYPE_R     1034
#define IDC_BUTTON_WS_OPEN_CLOSE        1035
#define IDC_EDIT_WS_WRITE               1036
#define IDC_CHECK_WS_CR                 1037
#define IDC_CHECK_WS_LF                 1038
#define IDC_BUTTON_WS_SEND              1039
#define IDC_BUTTON_WS_WRITE             1039
#define IDC_EDIT_SERIAL_SBIT2           1040
#define IDC_EDIT_SERIAL_PBIT2           1041
#define IDC_COMBO_SERIAL_DISPLAY_TYPE_W2 1042
#define IDC_COMBO_SERIAL_DISPLAY_TYPE_R2 1043
#define IDC_BUTTON_SERIAL_OPEN_CLOSE2   1044
#define IDC_EDIT_SERIAL_WRITE2          1045
#define IDC_CHECK_SERIAL_CR2            1046
#define IDC_CHECK_SERIAL_LF2            1047
#define IDC_BUTTON_SERIAL_WRITE2        1048
#define IDC_CHECK_SERIAL_ROUTER         1049
#define IDC_CHECK_NET_LOG               1050
#define IDC_CHECK_WS_LOG                1051
#define IDC_CHECK_SERIAL_LOG            1052
#define IDC_CHECK_SERIAL_LOG2           1053
#define IDC_CHECK_NET_ECHO              1054
#define IDC_CHECK_WS_ECHO               1055
#define IDC_CHECK_SERIAL_ECHO           1056
#define IDC_CHECK_SERIAL_ECHO2          1057
#define IDC_TAB_CONTROL                 1058
#define IDC_CHECK_NET_STX               1058
#define IDC_STATIC_DRAW_AXIS            1059
#define IDC_CHECK_NET_ETX               1059
#define IDC_EDIT_DRAW_ABS_COORD         1060
#define IDC_EDIT_DRAW_ABS_COORD_PICK    1061
#define IDC_CHECK_WS_STX                1061
#define IDC_EDIT_DRAW_REL_COORD         1062
#define IDC_CHECK_WS_ETX                1062
#define IDC_EDIT_DRAW_REL_COORD_PICK    1063
#define IDC_CHECK_SERIAL_STX            1063
#define IDC_EDIT_DRAW_SPORT             1064
#define IDC_CHECK_SERIAL_ETX            1064
#define IDC_EDIT_DRAW_REL_COORD2        1065
#define IDC_CHECK_SERIAL_STX2           1065
#define IDC_EDIT_DRAW_REL_COORD_PICK2   1066
#define IDC_CHECK_SERIAL_ETX2           1066
#define IDC_EDIT_DRAW_BAUD              1067
#define IDC_EDIT_DRAW_DBIT              1068
#define IDC_EDIT_DRAW_SBIT              1069
#define IDC_EDIT_DRAW_PBIT              1070
#define IDC_EDIT_DRAW_WRITE             1071
#define IDC_COMBO_DRAW_DISPLAY_TYPE_W   1072
#define IDC_COMBO_DRAW_DISPLAY_TYPE_R   1073
#define IDC_BUTTON_DRAW_OPEN_CLOSE      1074
#define IDC_BUTTON_DRAW_WRITE           1075
#define IDC_CHECK_DRAW_CR               1076
#define IDC_CHECK_DRAW_LF               1077
#define IDC_CHECK_DRAW_SERIAL_LOG       1078
#define IDC_CHECK_DRAW_SERIAL_ECHO      1079
#define IDC_LIST_DRAW_READ              1080
#define IDC_BUTTON_DRAW_CLEAR           1081
#define IDC_CHECK_DRAW_READ_YN          1082
#define IDC_EDIT_DRAW_ABS_COORD2        1083
#define IDC_STATIC_PRIMESET             1083
#define IDC_EDIT_DRAW_ABS_COORD_PICK2   1084
#define IDC_EDIT_PRIME_BEGIN            1084
#define IDC_EDIT_PRIME_END              1085
#define IDC_BUTTON_FIND                 1086
#define IDC_COMBO_PRIME_SET             1087
#define IDC_BUTTON_SELECT               1088
#define IDC_BUTTON_BITMAP_FILEOPEN      1088
#define IDC_EDIT_PRIMES                 1089
#define IDC_EDIT_BITMAP_FILE            1089
#define IDC_BUTTON_RESET                1090
#define IDC_STATIC_BITMAP_VIEW          1090
#define IDC_EDIT_GCM                    1091
#define IDC_BUTTON_BITMAP_CONVERT       1091
#define IDC_EDIT_LCD                    1092
#define IDC_EDIT_BITMAP_HEX             1092
#define IDC_EDIT_COMPOSITE              1093
#define IDC_EDIT_BITMAP_BMPHDR          1093
#define IDC_EDIT_WSC_END                1093
#define IDC_BUTTON_PRIME_FACTORS        1094
#define IDC_EDIT_BITMAP_HEADER2         1094
#define IDC_EDIT_BITMAP_DIBHDR          1094
#define IDC_EDIT_WSC_BEGIN              1094
#define IDC_EDIT_PRIME_FACTORS          1095
#define IDC_BUTTON_WSC_START            1095
#define IDC_STATIC_FACTORING            1096
#define IDC_BUTTON_WSC_STOP             1096
#define IDC_BUTTON_WSC_TIMER            1096
#define IDC_BUTTON_GCM_LCD              1097
#define IDC_EDIT_WSC_TIMER              1097
#define IDC_EDIT_RSA_PRIMES             1098
#define IDC_LIST2                       1098
#define IDC_LIST_WSC_LOG                1098
#define IDC_EDIT_COMMON_DIVISORS        1099
#define IDC_STATIC_WSC_MSEC             1099
#define IDC_BUTTON_COMMON_DIVISOR       1100
#define IDC_BUTTON_WSC_TIMER2           1100
#define IDC_BUTTON_WSC_CLEAR            1100
#define IDC_CHECK_SERIAL_SIMULA         1100
#define IDC_COMBO_COMPOSITE_FACTOR      1101
#define IDC_EDIT_SERIAL_MSEC            1101
#define IDC_BUTTON_DIVISOR              1102
#define IDC_LIST_WSGW_TCP_LOG           1102
#define IDC_CHECK_WS_SIMULA             1102
#define IDC_EDIT_DIVISORS               1103
#define IDC_BUTTON_WSGW_START           1103
#define IDC_CHECK_NET_SIMULA            1103
#define IDC_NET_CHECK_SIMULA            1103
#define IDC_STATIC_FACTORING2           1104
#define IDC_BUTTON_WSGW_CLEAR           1104
#define IDC_EDIT_NET_MSEC               1104
#define IDC_NET_EDIT_MSEC               1104
#define IDC_EDIT_RSA_EULER_N            1105
#define IDC_LIST_WSGW_WS_LOG            1105
#define IDC_EDIT_NET_MSEC2              1105
#define IDC_EDIT_WS_MSEC                1105
#define IDC_BUTTON_RSA_EULER_N          1106
#define IDC_EDIT_WSGW_TCP_PORT          1106
#define IDC_EDIT_RSA_N                  1107
#define IDC_EDIT2                       1107
#define IDC_EDIT_WSGW_WS_PORT           1107
#define IDC_BUTTON_RSA_N                1108
#define IDC_COMBO_COMPOSITE_FACTOR2     1108
#define IDC_COMBO_RSA_E                 1108
#define IDC_CHECK_WSGW_LOG              1108
#define IDC_EDIT_RSA_E                  1109
#define IDC_COMBO_DISPLAY_TYPE_WSGW     1109
#define IDC_CHECK_WSGW_REQ              1109
#define IDC_BUTTON_RSA_E                1110
#define IDC_EDIT_WSGW_MSEC              1110
#define IDC_EDIT_RSA_D                  1111
#define IDC_LIST_WSGW_TCP_LOG2          1111
#define IDC_LIST_WSGW_DB_LOG            1111
#define IDC_EDIT1                       1111
#define IDC_EDIT_LIST_COUNT             1111
#define IDC_BUTTON_RSA_D                1112
#define IDC_EDIT_RSA_D_ORG              1112
#define IDC_EDIT_RSA_PUBKEY             1113
#define IDC_EDIT_RSA_PRIKEY             1114
#define IDC_BUTTON_RSA_KEY              1115
#define IDC_EDIT_RSA_CLEAR_TEXT         1116
#define IDC_EDIT_RSA_ENCODE             1117
#define IDC_EDIT_RSA_DECODE             1118
#define IDC_BUTTON_RSA_ENCODE           1119
#define IDC_BUTTON_RSA_DECODE           1120
#define IDC_EDIT_RSA_EULER_N_HEX        1121
#define IDC_EDIT_RSA_N2                 1122
#define IDC_EDIT_RSA_N_HEX              1122

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1112
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
