#! /bin/bash

if [ $1 == "all" -o $1 == "x32" ]
then
CLFAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 CROSS_COMPILE=no ARCH_TYPE=x32 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 DEBUG=0 make clean;
CLFAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 CROSS_COMPILE=no ARCH_TYPE=x32 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 DEBUG=0 make dir;
CLFAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 CROSS_COMPILE=no ARCH_TYPE=x32 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 DEBUG=0 make all;
\cp -rfp ../../lite.io/x32/sifr.kit.so ./out
fi

if [ $1 == "all" -o $1 == "x64" ]
then
CLFAGS=-m64 CXXFLAGS=-m64 LDFLAGS=-m64 CROSS_COMPILE=no ARCH_TYPE=x64 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 DEBUG=0 make clean;
CLFAGS=-m64 CXXFLAGS=-m64 LDFLAGS=-m64 CROSS_COMPILE=no ARCH_TYPE=x64 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 DEBUG=0 make dir;
CLFAGS=-m64 CXXFLAGS=-m64 LDFLAGS=-m64 CROSS_COMPILE=no ARCH_TYPE=x64 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 DEBUG=0 make all;
\cp -rfp ../../lite.io/x64/sifr.kit.so ./out
fi


if [ $1 == "all" -o $1 == "a32" ]
then
CROSS_COMPILE=yes ARCH_TYPE=a32 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=SOFT DEBUG=0 make clean;
CROSS_COMPILE=yes ARCH_TYPE=a32 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=SOFT DEBUG=0 make dir;
CROSS_COMPILE=yes ARCH_TYPE=a32 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=SOFT DEBUG=0 make all;
\cp -rfp ../../lite.io/a32/sifr.kit.so ./out
fi

if [ $1 == "all" -o $1 == "a64" ]
then
CROSS_COMPILE=yes ARCH_TYPE=a64 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=SOFT DEBUG=0 make clean;
CROSS_COMPILE=yes ARCH_TYPE=a64 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=SOFT DEBUG=0 make dir;
CROSS_COMPILE=yes ARCH_TYPE=a64 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=SOFT DEBUG=0 make all;
\cp -rfp ../../lite.io/a64/sifr.kit.so ./out
fi

if [ $1 == "all" -o $1 == "ha32" ]
then
CROSS_COMPILE=yes ARCH_TYPE=a32 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=HARD DEBUG=0 make clean;
CROSS_COMPILE=yes ARCH_TYPE=a32 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=HARD DEBUG=0 make dir;
CROSS_COMPILE=yes ARCH_TYPE=a32 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=HARD DEBUG=0 make all;
\cp -rfp ../../lite.io/ha32/sifr.kit.so ./out
fi

if [ $1 == "all" -o $1 == "ha64" ]
then
CROSS_COMPILE=yes ARCH_TYPE=a64 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=HARD DEBUG=0 make clean;
CROSS_COMPILE=yes ARCH_TYPE=a64 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=HARD DEBUG=0 make dir;
CROSS_COMPILE=yes ARCH_TYPE=a64 OUTPUT_TYPE=.out OUTPUT_NAME=cCrypto32 ABI=HARD DEBUG=0 make all;
\cp -rfp ../../lite.io/ha64/sifr.kit.so ./out
fi

